### PR TITLE
replace unit GB with GiB

### PR DESCRIPTION
**Pull request by SHuang-Broad**
Kiran, if you've been working on other branches, you'd probably want to rebase first, as this touches practically every file and you'd also prefer using the new unit, just to avoid that edge case we saw in PBSV.

### CODE REVIEW

**Comment by SHuang-Broad** [comment]
__HOLD__. I've noticed another tricky thing about disk specification.
Running an experiment to try out.

**Comment by kvg** [comment]
Is this hold still active or is this branch ready to be merged?

**Comment by SHuang-Broad** [comment]
Let's wait a little.
I haven't got time to get back and made sure this is working for PBSV yet.

**Comment by kvg** [comment]
What's the current thinking on this PR?  I think it's out of date, but also it wasn't clear that switching from GB to GiB units actually solved the PBSV problem.  Shall we move this and start a separate investigation of PBSV problems?

**Comment by SHuang-Broad** [comment]
Agree.

Closing as there's not much value in this PR anymore.

**Pull request closed without merging**
